version: 'buildnumber.{build}'

image: Visual Studio 2019

configuration: Release

platform: Any CPU

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./WebHDFS.Kitty.sln

build_script:
  - cmd: dotnet build ./WebHDFS.Kitty.sln  --configuration Release
  - cmd: dotnet pack ./WebHDFS.Kitty.sln  --configuration Release

test_script:
  - cmd: dotnet test ./WebHDFS.Kitty.IntegrationTests/WebHDFS.Kitty.IntegrationTests.csproj
  
artifacts:
  - path: '**\*.nupkg'
    type: 'NuGetPackage'
